/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyecto.vista;

import com.proyecto.beans.Usuario;
import com.proyecto.main.Login;
import com.proyecto.reportes.ReporteBienesXAmbiente;
import com.proyecto.reportes.ReporteStickers;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Documentos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        File file = new File("img/iconos/inventarios.jpg");
        ImagenFondo borde;
        try {
            borde = new ImagenFondo(ImageIO.read(file));
            desktoppane.setBorder(borde);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        System.out.println("USUARIO ACTUAL: " + UsuarioUtil.getUsuarioActual().getNombre());

        if (UsuarioUtil.getUsuarioActual().getTipoUsuario().getId()==1) {
            menuUsuario.setEnabled(true);
            menuTipoUsuario.setEnabled(true);
        } else {
            menuUsuario.setEnabled(false);
            menuTipoUsuario.setEnabled(false);
        }
        
        Usuario user = UsuarioUtil.getUsuarioActual();
        
        jMenuTxt.setText(" Usuario: "+ user.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktoppane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        menuMantenimiento = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuCampo = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuTipoUsuario = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuTxt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE PATRIMONIO v2.0");
        setIconImage(new javax.swing.ImageIcon("img/iconos/logo.png").getImage());

        desktoppane.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);

        javax.swing.GroupLayout desktoppaneLayout = new javax.swing.GroupLayout(desktoppane);
        desktoppane.setLayout(desktoppaneLayout);
        desktoppaneLayout.setHorizontalGroup(
            desktoppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        desktoppaneLayout.setVerticalGroup(
            desktoppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon("img/iconos/Actividad.png"));
        jMenu1.setText("Actividades");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon("img/iconos/Refresh.png"));
        jMenuItem7.setText("Actualizar Inventario");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon("img/iconos/Warning.png"));
        jMenuItem12.setText("Prueba");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuBar1.add(jMenu1);

        menuMantenimiento.setIcon(new javax.swing.ImageIcon("img/iconos/Settings.png"));
        menuMantenimiento.setText("Mantenimiento");
        menuMantenimiento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon("img/iconos/Stop.png"));
        jMenuItem1.setText("Ambiente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem1);

        jMenuItem8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon("img/iconos/Location_2-20.png"));
        jMenuItem8.setText("Área");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem8);

        jMenuItem2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon("img/iconos/cardboard-box-20.png"));
        jMenuItem2.setText("Bien");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem2);

        MenuCampo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MenuCampo.setIcon(new javax.swing.ImageIcon("img/iconos/campo.png"));
        MenuCampo.setText("Campo");
        MenuCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCampoActionPerformed(evt);
            }
        });
        menuMantenimiento.add(MenuCampo);

        jMenuItem3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon("img/iconos/clase.png"));
        jMenuItem3.setText("Clase");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem3);

        jMenuItem9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon("img/iconos/personal.png"));
        jMenuItem9.setText("Empleado");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem9);

        jMenuItem14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem14.setIcon(new javax.swing.ImageIcon("img/iconos/Sales-by-Payment-Method-rep.png"));
        jMenuItem14.setText("Factura");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem14);

        jMenuItem4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon("img/iconos/inventario.png"));
        jMenuItem4.setText("Inventario");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem4);

        jMenuItem6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon("img/iconos/periodo.png"));
        jMenuItem6.setText("Periodo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem6);

        jMenuItem13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon("img/iconos/provider.png"));
        jMenuItem13.setText("Proveedor");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem13);

        jMenuItem5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon("img/iconos/tipo.png"));
        jMenuItem5.setText("Tipo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem5);

        menuTipoUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        menuTipoUsuario.setIcon(new javax.swing.ImageIcon("img/iconos/tipo de user.png"));
        menuTipoUsuario.setText("Tipo de Usuario");
        menuTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTipoUsuarioActionPerformed(evt);
            }
        });
        menuMantenimiento.add(menuTipoUsuario);

        menuUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        menuUsuario.setIcon(new javax.swing.ImageIcon("img/iconos/user.png"));
        menuUsuario.setText("Usuario");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        menuMantenimiento.add(menuUsuario);

        jMenuBar1.add(menuMantenimiento);

        jMenu3.setIcon(new javax.swing.ImageIcon("img/iconos/edit-paste.png"));
        jMenu3.setText("Reportes");
        jMenu3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem11.setText("Reporte de bienes");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem15.setText("Reporte de códigos de barras");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem15);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon("img/iconos/Log Out.png"));
        jMenu4.setText("Cerrar Sesión");
        jMenu4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon("img/iconos/logoutmenu.png"));
        jMenuItem10.setText("Cerrar");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        jMenuTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTxtActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuTxt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktoppane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktoppane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        MantenimientoAmbiente ambiente = MantenimientoAmbiente.getInstancia();
        if (!this.desktoppane.isAncestorOf(ambiente)) {
            this.desktoppane.add(ambiente);
            ambiente.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        MantenimientoBien bien = MantenimientoBien.getInstancia();
        if (!this.desktoppane.isAncestorOf(bien)) {
            this.desktoppane.add(bien);
            bien.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        MantenimientoClase clase = MantenimientoClase.getInstancia();
        if (!this.desktoppane.isAncestorOf(clase)) {
            this.desktoppane.add(clase);
            clase.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        MantenimientoInventario inventaario = MantenimientoInventario.getInstancia();
        if (!this.desktoppane.isAncestorOf(inventaario)) {
            this.desktoppane.add(inventaario);
            inventaario.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
//         TODO add your handling code here:
        MantenimientoTipo tipo = MantenimientoTipo.getInstancia();
        if (!this.desktoppane.isAncestorOf(tipo)) {
            this.desktoppane.add(tipo);
            tipo.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        MantenimientoPeriodo periodo = MantenimientoPeriodo.getInstancia();
        if (!this.desktoppane.isAncestorOf(periodo)) {
            this.desktoppane.add(periodo);
            periodo.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        ActualizarInventario inventario = ActualizarInventario.getInstancia();
        if (!this.desktoppane.isAncestorOf(inventario)) {
            this.desktoppane.add(inventario);
            inventario.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        MantenimientoArea area = MantenimientoArea.getInstancia();
        if (!this.desktoppane.isAncestorOf(area)) {
            this.desktoppane.add(area);
            area.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        MantenimientoEmpleado empleado = MantenimientoEmpleado.getInstancia();
        if (!this.desktoppane.isAncestorOf(empleado)) {
            this.desktoppane.add(empleado);
            empleado.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "¿Desea salir del sistema?", "Mensaje del Sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.dispose();
            jMenuTxt.setText(null);
            Login login = new Login();
            login.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "okis", "Mensaje del Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void menuTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTipoUsuarioActionPerformed
        // TODO add your handling code here:
        MantenimientoTipoUsuario tipoUsuario = MantenimientoTipoUsuario.getInstancia();
        if (!this.desktoppane.isAncestorOf(tipoUsuario)) {
            this.desktoppane.add(tipoUsuario);
            tipoUsuario.setVisible(true);
        }
    }//GEN-LAST:event_menuTipoUsuarioActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        // TODO add your handling code here:
        MantenimientoUsuario usuario = MantenimientoUsuario.getInstancia();
        if (!this.desktoppane.isAncestorOf(usuario)) {
            this.desktoppane.add(usuario);
            usuario.setVisible(true);
        }
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        MantenimientoProveedor proveedor = MantenimientoProveedor.getInstancia();
        if (!this.desktoppane.isAncestorOf(proveedor)) {
            this.desktoppane.add(proveedor);
            proveedor.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void MenuCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCampoActionPerformed
        // TODO add your handling code here:
        MantenimientoCampo campo = MantenimientoCampo.getInstancia();
        if (!this.desktoppane.isAncestorOf(campo)) {
            this.desktoppane.add(campo);
            campo.setVisible(true);
        }
    }//GEN-LAST:event_MenuCampoActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        MantenimientoFactura factura = MantenimientoFactura.getInstancia();
        if (!this.desktoppane.isAncestorOf(factura)) {
            this.desktoppane.add(factura);
            factura.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuTxtActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        PruebaAmbienteInventario prueba = PruebaAmbienteInventario.getInstancia();
        if (!this.desktoppane.isAncestorOf(prueba)) {
            this.desktoppane.add(prueba);
            prueba.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        ReporteBienesXAmbiente reporte = ReporteBienesXAmbiente.getInstance();
        agregarAPanel(reporte);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        ReporteStickers rs = new ReporteStickers();
        agregarAPanel(rs);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void agregarAPanel(JInternalFrame internal){
        if (!this.desktoppane.isAncestorOf(internal)) {
            this.desktoppane.add(internal);
            internal.setVisible(true);
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Principal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCampo;
    public static javax.swing.JDesktopPane desktoppane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMenuTxt;
    private javax.swing.JMenu menuMantenimiento;
    private javax.swing.JMenuItem menuTipoUsuario;
    private javax.swing.JMenuItem menuUsuario;
    // End of variables declaration//GEN-END:variables
}
